<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DataSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('data')->truncate();

        DB::table('data')->insert([
            [
                'user_id' => 1,
                'nama' => 'Argadia Bagus Wirawan',
                'nik' => 123456,
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '2000-02-22',
                'jenis_kelamin' => 'Laki-laki',
                'alamat' => 'Halim',
                'rt' => '69',
                'rw' => '69',
                'kelurahan' => 'Jakarta',
                'kecamatan' => 'Jakarta',
                'kota' => 'Jakarta',
                'provinsi' => 'Jakarta Timur',
                'agama' => 'Islam',
                'status_perkawinan' => 'Belum Menikah',
                'pekerjaan' => 'Apa aja',
                'kewarganegaraan' => 'Indonesia',
                'nomor_hp' => '081314131106',
                'email' => 'argadiabagus@gmail.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'nama' => 'Nadia Wirawan',
                'nik' => 543210,
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '1998-05-12',
                'jenis_kelamin' => 'Perempuan',
                'alamat' => 'Antapani',
                'rt' => '12',
                'rw' => '05',
                'kelurahan' => 'Antapani',
                'kecamatan' => 'Antapani',
                'kota' => 'Bandung',
                'provinsi' => 'Jawa Barat',
                'agama' => 'Islam',
                'status_perkawinan' => 'Menikah',
                'pekerjaan' => 'Guru',
                'kewarganegaraan' => 'Indonesia',
                'nomor_hp' => '081234567890',
                'email' => 'nadia.wirawan@gmail.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 3,
                'nama' => 'Budi Setiawan',
                'nik' => 987654,
                'tempat_lahir' => 'Surabaya',
                'tanggal_lahir' => '1995-07-14',
                'jenis_kelamin' => 'Laki-laki',
                'alamat' => 'Wonokromo',
                'rt' => '45',
                'rw' => '10',
                'kelurahan' => 'Wonokromo',
                'kecamatan' => 'Wonokromo',
                'kota' => 'Surabaya',
                'provinsi' => 'Jawa Timur',
                'agama' => 'Islam',
                'status_perkawinan' => 'Menikah',
                'pekerjaan' => 'Karyawan Swasta',
                'kewarganegaraan' => 'Indonesia',
                'nomor_hp' => '081234567891',
                'email' => 'budi.setiawan@gmail.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 4,
                'nama' => 'Sri Rahayu',
                'nik' => 654321,
                'tempat_lahir' => 'Semarang',
                'tanggal_lahir' => '1990-11-23',
                'jenis_kelamin' => 'Perempuan',
                'alamat' => 'Banyumanik',
                'rt' => '18',
                'rw' => '02',
                'kelurahan' => 'Banyumanik',
                'kecamatan' => 'Banyumanik',
                'kota' => 'Semarang',
                'provinsi' => 'Jawa Tengah',
                'agama' => 'Islam',
                'status_perkawinan' => 'Menikah',
                'pekerjaan' => 'Dokter',
                'kewarganegaraan' => 'Indonesia',
                'nomor_hp' => '081234567892',
                'email' => 'sri.rahayu@gmail.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 5,
                'nama' => 'Dewi Putri',
                'nik' => 234567,
                'tempat_lahir' => 'Medan',
                'tanggal_lahir' => '1988-09-01',
                'jenis_kelamin' => 'Perempuan',
                'alamat' => 'Polonia',
                'rt' => '33',
                'rw' => '07',
                'kelurahan' => 'Polonia',
                'kecamatan' => 'Medan Baru',
                'kota' => 'Medan',
                'provinsi' => 'Sumatera Utara',
                'agama' => 'Kristen',
                'status_perkawinan' => 'Menikah',
                'pekerjaan' => 'Wiraswasta',
                'kewarganegaraan' => 'Indonesia',
                'nomor_hp' => '081234567893',
                'email' => 'dewi.putri@gmail.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Tambahkan 5 data lainnya dengan pola serupa
            [
                'user_id' => 6,
                'nama' => 'Andi Wijaya',
                'nik' => 345678,
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '1997-03-05',
                'jenis_kelamin' => 'Laki-laki',
                'alamat' => 'Umbulharjo',
                'rt' => '21',
                'rw' => '06',
                'kelurahan' => 'Umbulharjo',
                'kecamatan' => 'Umbulharjo',
                'kota' => 'Yogyakarta',
                'provinsi' => 'DI Yogyakarta',
                'agama' => 'Islam',
                'status_perkawinan' => 'Belum Menikah',
                'pekerjaan' => 'Mahasiswa',
                'kewarganegaraan' => 'Indonesia',
                'nomor_hp' => '081234567894',
                'email' => 'andi.wijaya@gmail.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 7,
                'nama' => 'Rizki Rahman',
                'nik' => 456789,
                'tempat_lahir' => 'Palembang',
                'tanggal_lahir' => '1996-12-30',
                'jenis_kelamin' => 'Laki-laki',
                'alamat' => 'Ilir Timur',
                'rt' => '24',
                'rw' => '08',
                'kelurahan' => 'Ilir Timur',
                'kecamatan' => 'Ilir Timur',
                'kota' => 'Palembang',
                'provinsi' => 'Sumatera Selatan',
                'agama' => 'Islam',
                'status_perkawinan' => 'Menikah',
                'pekerjaan' => 'Pengusaha',
                'kewarganegaraan' => 'Indonesia',
                'nomor_hp' => '081234567895',
                'email' => 'rizki.rahman@gmail.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 8,
                'nama' => 'Siti Nurhaliza',
                'nik' => 567890,
                'tempat_lahir' => 'Banda Aceh',
                'tanggal_lahir' => '1999-04-18',
                'jenis_kelamin' => 'Perempuan',
                'alamat' => 'Kuta Alam',
                'rt' => '29',
                'rw' => '10',
                'kelurahan' => 'Kuta Alam',
                'kecamatan' => 'Kuta Alam',
                'kota' => 'Banda Aceh',
                'provinsi' => 'Aceh',
                'agama' => 'Islam',
                'status_perkawinan' => 'Belum Menikah',
                'pekerjaan' => 'Mahasiswa',
                'kewarganegaraan' => 'Indonesia',
                'nomor_hp' => '081234567896',
                'email' => 'siti.nurhaliza@gmail.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 9,
                'nama' => 'Indra Kurniawan',
                'nik' => 678901,
                'tempat_lahir' => 'Makassar',
                'tanggal_lahir' => '1994-10-27',
                'jenis_kelamin' => 'Laki-laki',
                'alamat' => 'Panakkukang',
                'rt' => '31',
                'rw' => '11',
                'kelurahan' => 'Panakkukang',
                'kecamatan' => 'Panakkukang',
                'kota' => 'Makassar',
                'provinsi' => 'Sulawesi Selatan',
                'agama' => 'Islam',
                'status_perkawinan' => 'Menikah',
                'pekerjaan' => 'Dosen',
                'kewarganegaraan' => 'Indonesia',
                'nomor_hp' => '081234567897',
                'email' => 'indra.kurniawan@gmail.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 10,
                'nama' => 'Farah Amelia',
                'nik' => 789012,
                'tempat_lahir' => 'Malang',
                'tanggal_lahir' => '2001-08-15',
                'jenis_kelamin' => 'Perempuan',
                'alamat' => 'Blimbing',
                'rt' => '20',
                'rw' => '04',
                'kelurahan' => 'Blimbing',
                'kecamatan' => 'Blimbing',
                'kota' => 'Malang',
                'provinsi' => 'Jawa Timur',
                'agama' => 'Islam',
                'status_perkawinan' => 'Belum Menikah',
                'pekerjaan' => 'Pelajar',
                'kewarganegaraan' => 'Indonesia',
                'nomor_hp' => '081234567898',
                'email' => 'farah.amelia@gmail.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
